### ISSUE TITLE
multiple packages fail

### ISSUE THREAD

**Issue by bluelovers** [zkat/npx#157] opened 2018-02-07 19:30 UTC
```
npx --package rollup --package rollup-plugin-node-resolve --package rollup-plugin-commonjs -c "rollup -c"
```

> Error: Cannot find module 'rollup-plugin-node-resolve'

rollup.config.js
```js
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

var pkg = require('./package.json');

export default {
	input: 'index.js',
	name: pkg.name,
	plugins: [
		commonjs(),
		resolve(),
	],
	output: [
		{ file: pkg.main, format: 'umd' },
		{ file: pkg.module, format: 'es' },
	],
}
```

**Comment by zkat** [comment] 2018-05-03 22:12
So this isn't something npx supports right now -- `-p` makes the _binaries_ for that package available, not the library versions. I'm changing this, though, with #180 (assuming that lands), so this sort of thing will be possible.

**Comment by zkat** [comment] 2018-05-03 22:18
Closing this as a dupe of #153

**Closed as completed by zkat** 2018-05-03 22:18 UTC
Labels: enhancement
