### ISSUE TITLE
Avoid installation if same module is used multiple times

### ISSUE THREAD

**Issue by vjpr** [zkat/npx#123] opened 2017-10-17 15:11 UTC
If I run `npx cowsay@1 boo` twice in a row, it will always install twice...even if its installed globally.

Could we not compare that `package-lock.json` has not changed since the last install, and make it instant without needing to show a progress bar?

At the moment I see a ~2s delay each time I run this command (even with all deps cached). If I want to specifically run `cowsay@1`, I will always incur this penalty.

**Comment by zkat** [comment] 2017-11-06 23:43
This is a duplicate of #113

**Closed as completed by zkat** 2017-11-06 23:43 UTC
