### ISSUE TITLE
`npx uglify-js` and `npx uglifyjs` fails

### ISSUE THREAD

**Issue by ljharb** [zkat/npx#97] opened 2017-07-21 00:05 UTC
- `npx uglifyjs input.js` reports `not found: uglify-js`
 - `npx uglify-js input.js` reports `not found: uglify-js`
 - `npm install uglify-js && npx uglifyjs input.js` works

In other words, it seems that when the package name and the "bin" name are different, it breaks?

It'd be great if when there was only one "bin", it would quietly use it, and when there was more than one "bin", it prompted me asking which one i wanted to use :-D

**Comment by zkat** [comment] 2017-07-21 08:18
npx has supported this since [`npx@8.0.0`](https://github.com/zkat/npx/blob/latest/CHANGELOG.md#features-5). So, I'm gonna close this as fixed ;)

Note that this is also why `npx <gist-url>` works!

I have confirmed manually that `npx uglify-js index.js` does, indeed, work. The inverse (trying to call a binary instead of the package name, when the binary doesn't exist), is unlikely to ever be supported unless the registry somehow starts keeping track of binary names for all packages, which would be further complicated by the fact that multiple packages might be using the same binary names, etc.

**Closed as completed by zkat** 2017-07-21 08:18 UTC
Labels: enhancement

**Comment by ljharb** [comment] 2017-07-21 08:20
ah, thanks, i'm using the one that came with stock latest node.

Using the package name only is perfectly fine, thanks!!
