### ISSUE TITLE
Default installed version with node 8.4.0 on windows logs error.

### ISSUE THREAD

**Issue by ravshansbox** [zkat/npx#117] opened 2017-09-09 08:54 UTC
Default installed version with node 8.4.0 on windows logs error, maybe it's node installer problem, not sure.
<img width="751" alt="npx" src="https://user-images.githubusercontent.com/1499188/30238725-3479d04c-9566-11e7-806e-d50903301b1f.png">

**Comment by michaeljota** [comment] 2017-09-15 17:13
It has been fixed here, since 9.4.x I think. However, the issue is `node` shipping an "old" version of npm, 5.3.x, and the fix landed in npm at 5.4.x. So is up to `node` to upgrade npm and npx.

**Comment by zkat** [comment] 2017-09-15 17:36
I'm going to close this as a duplicate of #110 .

**Closed as completed by zkat** 2017-09-15 17:36 UTC
