### ISSUE TITLE
Run npx with custom npm registry: sinopia or verdaccio

### ISSUE THREAD

**Issue by IhostVlad** [zkat/npx#145] opened 2017-12-29 08:15 UTC
Now `npx` allows to run binary executables from npm packages only if they located at `repository.npmjs.com`. But it major circumstances, including CI/CD and local debugging purposes, often it's need to load packages from local or cooperative repository, served by [sinopia](https://github.com/rlidwka/sinopia) or [verdaccio](https://github.com/verdaccio/verdaccio)

CLI command `npx` should accept parameter, like `--registry`, how it's provided in pure `npm` command. Most likely this feature can be implemented at [this function](https://github.com/zkat/npx/blob/357e6abc49077d7e4325406852d182220816e4f2/index.js#L209) by inserting couple of lines with console argument `--registry` bypassing.

**Comment by dominykas** [comment] 2018-01-02 15:50
Sounds like a duplicate of https://github.com/zkat/npx/issues/133?

**Comment by zkat** [comment] 2018-02-07 15:44
Closing as duplicate

**Closed as completed by zkat** 2018-02-07 15:44 UTC
